// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxccayiejeaksgnaunoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Y2NheWllamVha3NnbmF1bm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NjMxMDQsImV4cCI6MjA3NTMzOTEwNH0.Nl5DhbKoBSSmNQ59AqdM2AmzVwlsrgbT1LUVyWXnWjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});